---
# tasks file for ./roles/networks
- name: network / ether / Create the ethernet device configuration
  template:
    src: ethernet_{{ ansible_os_family }}.j2
    dest: "{{ net_path }}/ifcfg-{{ item.device }}"
  with_items: "{{ network_ether_interfaces }}"
  register: ether_result

- name: network / ether / Reload ethernet interfaces
  shell: ifdown {{ item.item.device }}; ifup {{ item.item.device }}
  with_items: ether_result.results
  when: ether_result is defined and item.changed
