---
# tasks file for ./roles/networks
- name: network / main / Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: network / main / Install the required packages in Redhat
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ network_pkgs }}"
  when: ansible_os_family == 'RedHat'

- name: network / main / Install the required packages in Debian
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: "{{ network_pkgs }}"
  when: ansible_os_family == 'Debian'

- name: network / main / Setup the ethernet device
  include: roles/network/tasks/ether.yml
  when: network_ether_interfaces is defined

- name: network / main / Setup the bond device
  include: roles/network/tasks/bond.yml
  when: network_bond_interfaces is defined
