---
# vars file for ./roles/packages
github_base_path: "https://github.com"

packages_from_github:
  - info: { path: "{{ github_base_path }}/rainbow23/dotfiles.git", dir: "dotfiles" }
  - info: { path: "{{ github_base_path }}/tmux-plugins/tpm",       dir: ".tmux/plugins/tpm" }
