- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true
  remote_user: "{{ ansible_user }}"
  become_user: root
  vars:
    home_path: "/home/{{ ansible_user }}"
    # ansible_sudo_pass: 'ansible'
    # ansible_sudo_pass: 'fujimaguro'

  roles:
    - name: common/packages
      tags: packages
