---
# tasks file for ./roles/packages
- name: main / Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: debug
  debug:
    msg: "os family={{ ansible_os_family }}"
    msg: "required_packages item={{ item.value  }}"
  with_dict: '{{ required_packages }}'

- name: main / Update apt packages
  apt:
    update_cache: yes
    name: "{{ item.value }}"
    state: present
  with_dict: "{{ required_packages }}"
  when: ansible_os_family == 'Debian'

- block:
  - name: Has neovim Dir?
    stat:
      path: "/etc/yum.repos.d/dperson-neovim-epel-7.repo"
    register: neovim_path
  - name: Download neovim
    shell: |
      yum -y install epel-release
      curl -o /etc/yum.repos.d/dperson-neovim-epel-7.repo https://copr.fedorainfracloud.org/coprs/dperson/neovim/repo/epel-7/dperson-neovim-epel-7.repo
    args:
      executable: /bin/bash
    when: neovim_path.stat.exists == False
  - name: main / Install the yum packages
    yum:
      name: "{{ item.value }}"
      state: present
    with_dict: "{{ required_packages }}"
  when: ansible_os_family == 'RedHat'

- block:
  - name: homebrew update
    homebrew:
      update_homebrew: yes
  - name: main / Install homebrew packages
    homebrew:
      name: '{{ item.value }}'
      # state: '{{ item.state | default("present") }}'
    with_dict: '{{ required_packages }}'
  when: ansible_os_family == 'Darwin'

- name: main / Install packages from github
  git:
    repo: "{{ item.value.path }}"
    dest: "{{ home_path }}/{{ item.value.dir }}"
    force: yes
    update: yes
  become_user: "{{ ansible_user }}"
  # become_user: root
  with_dict: "{{ packages_from_github }}"
  notify:
    - Permission change to directories
    - Symlink

- name: force notify handler
  meta: flush_handlers

- name: dotfiles settings
  shell: |
    chmod -R 755 ~/dotfiles
    cd "{{ home_path }}/dotfiles"
    git checkout master
    ./install_vim.sh
    ./init.sh
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim +slient +PlugInstall +qall
  args:
    executable: /bin/zsh
  become_user: "{{ ansible_user }}"
